version: '3.10'
services:
  backend:
    build: .
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always
    ports:
      - "8000:8000"
  ####################
  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt